/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AccountDisputesRouteImport } from './routes/account.disputes'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminIdentityRouteImport } from './routes/admin.identity'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as CategoryCategorySlugRouteImport } from './routes/category.$categorySlug'
import { Route as ListingListingIdRouteImport } from './routes/listing.$listingId'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as SellIndexRouteImport } from './routes/sell.index'
import { Route as SellerSellerIdRouteImport } from './routes/seller.$sellerId'
import { Route as SellerDashboardRouteImport } from './routes/seller.dashboard'
import { Route as SellerListingsRouteImport } from './routes/seller.listings'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerPayoutsRouteImport } from './routes/seller.payouts'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDisputesRoute = AccountDisputesRouteImport.update({
  id: '/account/disputes',
  path: '/account/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdentityRoute = AdminIdentityRouteImport.update({
  id: '/admin/identity',
  path: '/admin/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySlugRoute = CategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingListingIdRoute = ListingListingIdRouteImport.update({
  id: '/listing/$listingId',
  path: '/listing/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSellerIdRoute = SellerSellerIdRouteImport.update({
  id: '/seller/$sellerId',
  path: '/seller/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerListingsRoute = SellerListingsRouteImport.update({
  id: '/seller/listings',
  path: '/seller/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/seller/orders',
  path: '/seller/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerPayoutsRoute = SellerPayoutsRouteImport.update({
  id: '/seller/payouts',
  path: '/seller/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/account/disputes': typeof AccountDisputesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/identity': typeof AdminIdentityRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/listing/$listingId': typeof ListingListingIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/listings': typeof SellerListingsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payouts': typeof SellerPayoutsRoute
  '/admin/': typeof AdminIndexRoute
  '/sell/': typeof SellIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/account/disputes': typeof AccountDisputesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/identity': typeof AdminIdentityRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/listing/$listingId': typeof ListingListingIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/listings': typeof SellerListingsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payouts': typeof SellerPayoutsRoute
  '/admin': typeof AdminIndexRoute
  '/sell': typeof SellIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/account/disputes': typeof AccountDisputesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/identity': typeof AdminIdentityRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/listing/$listingId': typeof ListingListingIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/listings': typeof SellerListingsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payouts': typeof SellerPayoutsRoute
  '/admin/': typeof AdminIndexRoute
  '/sell/': typeof SellIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/partner'
    | '/products'
    | '/register'
    | '/account/disputes'
    | '/account/orders'
    | '/admin/identity'
    | '/admin/moderation'
    | '/admin/orders'
    | '/category/$categorySlug'
    | '/listing/$listingId'
    | '/product/$productId'
    | '/seller/$sellerId'
    | '/seller/dashboard'
    | '/seller/listings'
    | '/seller/orders'
    | '/seller/payouts'
    | '/admin/'
    | '/sell/'
    | '/account/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/partner'
    | '/products'
    | '/register'
    | '/account/disputes'
    | '/account/orders'
    | '/admin/identity'
    | '/admin/moderation'
    | '/admin/orders'
    | '/category/$categorySlug'
    | '/listing/$listingId'
    | '/product/$productId'
    | '/seller/$sellerId'
    | '/seller/dashboard'
    | '/seller/listings'
    | '/seller/orders'
    | '/seller/payouts'
    | '/admin'
    | '/sell'
    | '/account/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/partner'
    | '/products'
    | '/register'
    | '/account/disputes'
    | '/account/orders'
    | '/admin/identity'
    | '/admin/moderation'
    | '/admin/orders'
    | '/category/$categorySlug'
    | '/listing/$listingId'
    | '/product/$productId'
    | '/seller/$sellerId'
    | '/seller/dashboard'
    | '/seller/listings'
    | '/seller/orders'
    | '/seller/payouts'
    | '/admin/'
    | '/sell/'
    | '/account/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  ProductsRoute: typeof ProductsRoute
  RegisterRoute: typeof RegisterRoute
  AccountDisputesRoute: typeof AccountDisputesRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AdminIdentityRoute: typeof AdminIdentityRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  CategoryCategorySlugRoute: typeof CategoryCategorySlugRoute
  ListingListingIdRoute: typeof ListingListingIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  SellerSellerIdRoute: typeof SellerSellerIdRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerListingsRoute: typeof SellerListingsRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerPayoutsRoute: typeof SellerPayoutsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SellIndexRoute: typeof SellIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/disputes': {
      id: '/account/disputes'
      path: '/account/disputes'
      fullPath: '/account/disputes'
      preLoaderRoute: typeof AccountDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/identity': {
      id: '/admin/identity'
      path: '/admin/identity'
      fullPath: '/admin/identity'
      preLoaderRoute: typeof AdminIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug': {
      id: '/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof CategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$listingId': {
      id: '/listing/$listingId'
      path: '/listing/$listingId'
      fullPath: '/listing/$listingId'
      preLoaderRoute: typeof ListingListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$sellerId': {
      id: '/seller/$sellerId'
      path: '/seller/$sellerId'
      fullPath: '/seller/$sellerId'
      preLoaderRoute: typeof SellerSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/listings': {
      id: '/seller/listings'
      path: '/seller/listings'
      fullPath: '/seller/listings'
      preLoaderRoute: typeof SellerListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/seller/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/payouts': {
      id: '/seller/payouts'
      path: '/seller/payouts'
      fullPath: '/seller/payouts'
      preLoaderRoute: typeof SellerPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  ProductsRoute: ProductsRoute,
  RegisterRoute: RegisterRoute,
  AccountDisputesRoute: AccountDisputesRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AdminIdentityRoute: AdminIdentityRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  CategoryCategorySlugRoute: CategoryCategorySlugRoute,
  ListingListingIdRoute: ListingListingIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  SellerSellerIdRoute: SellerSellerIdRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerListingsRoute: SellerListingsRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerPayoutsRoute: SellerPayoutsRoute,
  AdminIndexRoute: AdminIndexRoute,
  SellIndexRoute: SellIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
