/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GradingRouteImport } from './routes/grading'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AccountDisputesRouteImport } from './routes/account.disputes'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminIdentityRouteImport } from './routes/admin.identity'
import { Route as AdminInspectionsRouteImport } from './routes/admin.inspections'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminReturnsRouteImport } from './routes/admin.returns'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CategoryCategorySlugRouteImport } from './routes/category.$categorySlug'
import { Route as CreatorCreatorSlugRouteImport } from './routes/creator.$creatorSlug'
import { Route as ListingListingIdRouteImport } from './routes/listing.$listingId'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as SellIndexRouteImport } from './routes/sell.index'
import { Route as SellerSellerIdRouteImport } from './routes/seller.$sellerId'
import { Route as SellerAnalyticsRouteImport } from './routes/seller.analytics'
import { Route as SellerCreatorProfileRouteImport } from './routes/seller.creator-profile'
import { Route as SellerDashboardRouteImport } from './routes/seller.dashboard'
import { Route as SellerDisputesRouteImport } from './routes/seller.disputes'
import { Route as SellerListingsRouteImport } from './routes/seller.listings'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerPayoutsRouteImport } from './routes/seller.payouts'
import { Route as SellerStorefrontRouteImport } from './routes/seller.storefront'
import { Route as StoreStoreSlugRouteImport } from './routes/store.$storeSlug'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account.orders.$orderId'
import { Route as SellerInventoryImportRouteImport } from './routes/seller.inventory.import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GradingRoute = GradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDisputesRoute = AccountDisputesRouteImport.update({
  id: '/account/disputes',
  path: '/account/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/admin/disputes',
  path: '/admin/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdentityRoute = AdminIdentityRouteImport.update({
  id: '/admin/identity',
  path: '/admin/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInspectionsRoute = AdminInspectionsRouteImport.update({
  id: '/admin/inspections',
  path: '/admin/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/admin/listings',
  path: '/admin/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/admin/partners',
  path: '/admin/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/admin/promotions',
  path: '/admin/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/admin/returns',
  path: '/admin/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySlugRoute = CategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorCreatorSlugRoute = CreatorCreatorSlugRouteImport.update({
  id: '/creator/$creatorSlug',
  path: '/creator/$creatorSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingListingIdRoute = ListingListingIdRouteImport.update({
  id: '/listing/$listingId',
  path: '/listing/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSellerIdRoute = SellerSellerIdRouteImport.update({
  id: '/seller/$sellerId',
  path: '/seller/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerAnalyticsRoute = SellerAnalyticsRouteImport.update({
  id: '/seller/analytics',
  path: '/seller/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerCreatorProfileRoute = SellerCreatorProfileRouteImport.update({
  id: '/seller/creator-profile',
  path: '/seller/creator-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDisputesRoute = SellerDisputesRouteImport.update({
  id: '/seller/disputes',
  path: '/seller/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerListingsRoute = SellerListingsRouteImport.update({
  id: '/seller/listings',
  path: '/seller/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/seller/orders',
  path: '/seller/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerPayoutsRoute = SellerPayoutsRouteImport.update({
  id: '/seller/payouts',
  path: '/seller/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerStorefrontRoute = SellerStorefrontRouteImport.update({
  id: '/seller/storefront',
  path: '/seller/storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreStoreSlugRoute = StoreStoreSlugRouteImport.update({
  id: '/store/$storeSlug',
  path: '/store/$storeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const SellerInventoryImportRoute = SellerInventoryImportRouteImport.update({
  id: '/seller/inventory/import',
  path: '/seller/inventory/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/grading': typeof GradingRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/account/disputes': typeof AccountDisputesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/identity': typeof AdminIdentityRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/creator/$creatorSlug': typeof CreatorCreatorSlugRoute
  '/listing/$listingId': typeof ListingListingIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/creator-profile': typeof SellerCreatorProfileRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/disputes': typeof SellerDisputesRoute
  '/seller/listings': typeof SellerListingsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payouts': typeof SellerPayoutsRoute
  '/seller/storefront': typeof SellerStorefrontRoute
  '/store/$storeSlug': typeof StoreStoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/sell/': typeof SellIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/seller/inventory/import': typeof SellerInventoryImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/grading': typeof GradingRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/account/disputes': typeof AccountDisputesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/identity': typeof AdminIdentityRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/creator/$creatorSlug': typeof CreatorCreatorSlugRoute
  '/listing/$listingId': typeof ListingListingIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/creator-profile': typeof SellerCreatorProfileRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/disputes': typeof SellerDisputesRoute
  '/seller/listings': typeof SellerListingsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payouts': typeof SellerPayoutsRoute
  '/seller/storefront': typeof SellerStorefrontRoute
  '/store/$storeSlug': typeof StoreStoreSlugRoute
  '/admin': typeof AdminIndexRoute
  '/sell': typeof SellIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/seller/inventory/import': typeof SellerInventoryImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/grading': typeof GradingRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/account/disputes': typeof AccountDisputesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/identity': typeof AdminIdentityRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/creator/$creatorSlug': typeof CreatorCreatorSlugRoute
  '/listing/$listingId': typeof ListingListingIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/seller/analytics': typeof SellerAnalyticsRoute
  '/seller/creator-profile': typeof SellerCreatorProfileRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/disputes': typeof SellerDisputesRoute
  '/seller/listings': typeof SellerListingsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/payouts': typeof SellerPayoutsRoute
  '/seller/storefront': typeof SellerStorefrontRoute
  '/store/$storeSlug': typeof StoreStoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/sell/': typeof SellIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/seller/inventory/import': typeof SellerInventoryImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/grading'
    | '/login'
    | '/partner'
    | '/products'
    | '/register'
    | '/account/disputes'
    | '/account/orders'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/disputes'
    | '/admin/identity'
    | '/admin/inspections'
    | '/admin/listings'
    | '/admin/login'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/category/$categorySlug'
    | '/creator/$creatorSlug'
    | '/listing/$listingId'
    | '/product/$productId'
    | '/seller/$sellerId'
    | '/seller/analytics'
    | '/seller/creator-profile'
    | '/seller/dashboard'
    | '/seller/disputes'
    | '/seller/listings'
    | '/seller/orders'
    | '/seller/payouts'
    | '/seller/storefront'
    | '/store/$storeSlug'
    | '/admin/'
    | '/sell/'
    | '/account/orders/$orderId'
    | '/seller/inventory/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/grading'
    | '/login'
    | '/partner'
    | '/products'
    | '/register'
    | '/account/disputes'
    | '/account/orders'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/disputes'
    | '/admin/identity'
    | '/admin/inspections'
    | '/admin/listings'
    | '/admin/login'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/category/$categorySlug'
    | '/creator/$creatorSlug'
    | '/listing/$listingId'
    | '/product/$productId'
    | '/seller/$sellerId'
    | '/seller/analytics'
    | '/seller/creator-profile'
    | '/seller/dashboard'
    | '/seller/disputes'
    | '/seller/listings'
    | '/seller/orders'
    | '/seller/payouts'
    | '/seller/storefront'
    | '/store/$storeSlug'
    | '/admin'
    | '/sell'
    | '/account/orders/$orderId'
    | '/seller/inventory/import'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/grading'
    | '/login'
    | '/partner'
    | '/products'
    | '/register'
    | '/account/disputes'
    | '/account/orders'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/disputes'
    | '/admin/identity'
    | '/admin/inspections'
    | '/admin/listings'
    | '/admin/login'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/category/$categorySlug'
    | '/creator/$creatorSlug'
    | '/listing/$listingId'
    | '/product/$productId'
    | '/seller/$sellerId'
    | '/seller/analytics'
    | '/seller/creator-profile'
    | '/seller/dashboard'
    | '/seller/disputes'
    | '/seller/listings'
    | '/seller/orders'
    | '/seller/payouts'
    | '/seller/storefront'
    | '/store/$storeSlug'
    | '/admin/'
    | '/sell/'
    | '/account/orders/$orderId'
    | '/seller/inventory/import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  GradingRoute: typeof GradingRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  ProductsRoute: typeof ProductsRoute
  RegisterRoute: typeof RegisterRoute
  AccountDisputesRoute: typeof AccountDisputesRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminIdentityRoute: typeof AdminIdentityRoute
  AdminInspectionsRoute: typeof AdminInspectionsRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CategoryCategorySlugRoute: typeof CategoryCategorySlugRoute
  CreatorCreatorSlugRoute: typeof CreatorCreatorSlugRoute
  ListingListingIdRoute: typeof ListingListingIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  SellerSellerIdRoute: typeof SellerSellerIdRoute
  SellerAnalyticsRoute: typeof SellerAnalyticsRoute
  SellerCreatorProfileRoute: typeof SellerCreatorProfileRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerDisputesRoute: typeof SellerDisputesRoute
  SellerListingsRoute: typeof SellerListingsRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerPayoutsRoute: typeof SellerPayoutsRoute
  SellerStorefrontRoute: typeof SellerStorefrontRoute
  StoreStoreSlugRoute: typeof StoreStoreSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SellIndexRoute: typeof SellIndexRoute
  SellerInventoryImportRoute: typeof SellerInventoryImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grading': {
      id: '/grading'
      path: '/grading'
      fullPath: '/grading'
      preLoaderRoute: typeof GradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/disputes': {
      id: '/account/disputes'
      path: '/account/disputes'
      fullPath: '/account/disputes'
      preLoaderRoute: typeof AccountDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/admin/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/identity': {
      id: '/admin/identity'
      path: '/admin/identity'
      fullPath: '/admin/identity'
      preLoaderRoute: typeof AdminIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inspections': {
      id: '/admin/inspections'
      path: '/admin/inspections'
      fullPath: '/admin/inspections'
      preLoaderRoute: typeof AdminInspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/admin/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug': {
      id: '/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof CategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$creatorSlug': {
      id: '/creator/$creatorSlug'
      path: '/creator/$creatorSlug'
      fullPath: '/creator/$creatorSlug'
      preLoaderRoute: typeof CreatorCreatorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$listingId': {
      id: '/listing/$listingId'
      path: '/listing/$listingId'
      fullPath: '/listing/$listingId'
      preLoaderRoute: typeof ListingListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$sellerId': {
      id: '/seller/$sellerId'
      path: '/seller/$sellerId'
      fullPath: '/seller/$sellerId'
      preLoaderRoute: typeof SellerSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/analytics': {
      id: '/seller/analytics'
      path: '/seller/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof SellerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/creator-profile': {
      id: '/seller/creator-profile'
      path: '/seller/creator-profile'
      fullPath: '/seller/creator-profile'
      preLoaderRoute: typeof SellerCreatorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/disputes': {
      id: '/seller/disputes'
      path: '/seller/disputes'
      fullPath: '/seller/disputes'
      preLoaderRoute: typeof SellerDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/listings': {
      id: '/seller/listings'
      path: '/seller/listings'
      fullPath: '/seller/listings'
      preLoaderRoute: typeof SellerListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/seller/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/payouts': {
      id: '/seller/payouts'
      path: '/seller/payouts'
      fullPath: '/seller/payouts'
      preLoaderRoute: typeof SellerPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/storefront': {
      id: '/seller/storefront'
      path: '/seller/storefront'
      fullPath: '/seller/storefront'
      preLoaderRoute: typeof SellerStorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$storeSlug': {
      id: '/store/$storeSlug'
      path: '/store/$storeSlug'
      fullPath: '/store/$storeSlug'
      preLoaderRoute: typeof StoreStoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/seller/inventory/import': {
      id: '/seller/inventory/import'
      path: '/seller/inventory/import'
      fullPath: '/seller/inventory/import'
      preLoaderRoute: typeof SellerInventoryImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  GradingRoute: GradingRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  ProductsRoute: ProductsRoute,
  RegisterRoute: RegisterRoute,
  AccountDisputesRoute: AccountDisputesRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminIdentityRoute: AdminIdentityRoute,
  AdminInspectionsRoute: AdminInspectionsRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  CategoryCategorySlugRoute: CategoryCategorySlugRoute,
  CreatorCreatorSlugRoute: CreatorCreatorSlugRoute,
  ListingListingIdRoute: ListingListingIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  SellerSellerIdRoute: SellerSellerIdRoute,
  SellerAnalyticsRoute: SellerAnalyticsRoute,
  SellerCreatorProfileRoute: SellerCreatorProfileRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerDisputesRoute: SellerDisputesRoute,
  SellerListingsRoute: SellerListingsRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerPayoutsRoute: SellerPayoutsRoute,
  SellerStorefrontRoute: SellerStorefrontRoute,
  StoreStoreSlugRoute: StoreStoreSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  SellIndexRoute: SellIndexRoute,
  SellerInventoryImportRoute: SellerInventoryImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
